# Practicing NumPy Library

NumPy is a library well suited for scientific computing. NumPy stores data in arrays in all dimensions, so why not just use lists? Well, Numpy is a lot faster! Also, NumPy can do exactly the same as lists and a lot more. 

A good example of NumPy usability could be as easy as wanting to multiply all elements of a list together. With normal lists you would have to for loop for each element since you cannot multiply lists. However in NumPy you could do it like this

In [1]:
# Importing NumPy

import numpy as np 

a = np.array([1,3,5])
b = np.array([1,2,5])

a*b

array([ 1,  6, 25])

Other applications are mathematical functions, plotting (matplotlib), Pandas and even Machine Learning!

Lets look at this library and it's useful functionalities. 

# Basics

In [15]:
# A basic array similar to a list

a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
# A two dimensional array 

b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [10]:
# Get Dimension 

a.ndim, b.ndim

(1, 2)

In [11]:
# Get Shape 

b.shape

(2, 3)

In [12]:
# Get Type

a.dtype

dtype('int64')

In [16]:
# Get Size 

a.itemsize

8

In [18]:
# Total Size 

a.itemsize

8

# Accessing/changing elements, rows, columns

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# Get a specific element [r,c]

a[1, 5]

13

In [22]:
# Get a specific row 

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [24]:
# More advanced [startindex:endindex:stepsize]

a[0, 1:6:2]

array([2, 4, 6])

# Initializing Different Types of Arrays 

In [33]:
# All 0s matrix

np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
# Another number

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [41]:
# Random numbers in [0,1]

np.random.rand(4,2)

array([[0.45396224, 0.34269895],
       [0.83663745, 0.16258662],
       [0.8774979 , 0.08601058],
       [0.78664153, 0.1324643 ]])

In [44]:
# Random integers 

np.random.randint(7, size=(3,3))

array([[5, 5, 1],
       [2, 6, 2],
       [1, 5, 0]])

In [46]:
# Identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Mathematical functionalities

In [56]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [58]:
# Addition

a + 2

array([3, 4, 5, 6])

In [61]:
# Subtraction 

a - 2

array([-1,  0,  1,  2])

In [62]:
# Multiplication 

a * 2 

array([2, 4, 6, 8])

In [63]:
# Division 

a / 2 

array([0.5, 1. , 1.5, 2. ])

In [86]:
#We already see here that it is quite smart to use arrays for
#multiplications etc. instead of for-loops. Example: 

from matplotlib import pyplot as plt

time = [1,2,3,4,5]
returns = [0.1,0.05,-0.1,0.01,0.2]

x = np.array(time)
y = np.array(returns)
w = np.array([1,1,1,1,1])

wealth = w * (1+y)
wealth

array([1.1 , 1.05, 0.9 , 1.01, 1.2 ])

In [82]:
# Squaring 

a ** 2

array([ 1,  4,  9, 16])

# Statistics

In [83]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
# Minimum value

np.min(stats)

1

In [85]:
# Max value in first row

np.max(stats, axis=1)

array([3, 6])

# Takeaways

After looking at NumPy for at bit and some of the endless functionalities I realize that the arrays are definitely smart, and also way smarter than lists. The key takeaway for me here is to convert lists to arrays when I need to do math operations on each element inside. Oftentimes I have found myself doing for-loops to iterate through the i list elements but luckily I will never have to do that again now! Looking at this library was time well spent. 